### ISSUE TITLE
Categorize building status

### ISSUE THREAD

**Issue by daguar** [openoakland/soft-story-alameda#21]
Need to combine the plain-text into the key categories:
- [x] Create the categories
- [x] Data cleaning (map the dirty data to the categories)

**Comment by daguar** [comment]
(Flushed out this issue)

**Comment by jnmarcus** [comment]
@dmieler my notes from last night say the four categories are:
- Potential Soft Story Building
- Not Soft Story Building
- Soft Story Building
- Retrofitted & Rehabilitated

Any changes or updates you want to make? Or is this what you what want to move forward with for now?

**Comment by dmieler** [comment]
This looks good. I think the fourth category can just be retrofitted, not
rehabilitated.

On Wed, Jan 21, 2015 at 1:46 PM, jnmarcus notifications@github.com wrote:

> @dmieler https://github.com/dmieler my notes from last night say the
> four categories are:
> - Potential Soft Story Building
> - Not Soft Story Building
> - Soft Story Building
> - Retrofitted & Rehabilitated
> 
> Any changes or updates you want to make? Or is this what you what want to
> move forward with for now?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openoakland/soft-story-alameda/issues/21#issuecomment-70928235
> .

## 

Danielle

**Comment by daguar** [comment]
So @dmieler, I have a weird one for you:

`SOFT STORY BUILDING - RETROFITTED UNDER PERMIT #B09-0486      NOT A SOFT STORY BUILDING PER ORDIANCE #2989`

That feels like it should be 'retrofitted', but I wanted to get your take. If you'd like I can look up which one that is, but I'm just finishing up bucketing them all.

**Comment by daguar** [comment]
I've written a `getStatus` function that categorizes these (in js/helpers.js), so I'm going to close this issue and open a new one for the weird one I mentioned above.

**Comment by dmieler** [comment]
That is pretty weird. I'd guess retrofitted too. I'll check with Greg. 

Danielle
